### ISSUE TITLE
Missing CONTRIBUTING.md file

### ISSUE THREAD

**Issue by lazyfuhrer** [eduardconstantin/Top-three-crypto#1]
Hey @eduardconstantin. Can I add the contributing.md file ? please assign me

**Comment by eduardconstantin** [comment]
Sure

**Comment by lazyfuhrer** [comment]
PR sent @eduardconstantin

**Comment by eduardconstantin** [comment]
@lazyfuhrer use this file https://github.com/eduardconstantin/Crypto-Rankings/blob/main/CONTRIBUTING.md
