### ISSUE TITLE
Create code of conduct file

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/Top-three-crypto#2]
Add a CODE_OF_CONDUCT.md file to the project

**Comment by FaithKovi** [comment]
Hello, @eduardconstantin I will like to work on this issue. Are there any specifications on what you want in the Code of Conduct?

**Comment by eduardconstantin** [comment]
@FaithKovi you can use this one https://github.com/eduardconstantin/Crypto-Rankings/blob/main/CODE_OF_CONDUCT.md
there is a file created just modify it

**Comment by FaithKovi** [comment]
Okay, @eduardconstantin  Thank you.

**Comment by FaithKovi** [comment]
@eduardconstantin I have modified it by working on the structure of the contents. I created a pull request.
